### ISSUE TITLE
PHP 7.4.20 and Nginx problem

### ISSUE THREAD

**Issue by EthraZa** [taq/phpreports#8]
Since I have migrated from PHP5+Apache to PHP7+Nginx I'm having the same problem but was ignoring it. (Maybe it add something to #7)

I'm getting lots of warnings and errors on logs but since the report seems to be working I just ignored it because of lack of time. But today someone needed the CSV report and this errors may be linked to the problem I'm, facing now.

When I generate the report (paginated/complete), it seems good (dispite the PHP errors/warnings and the accentuation problem).  When I change it to CSV, it may looks good, but the line brakes are gonne, making it look like a single line file.

It may be or may be not linked to the accentuation problem but, since I have no idea where to look for it, I can't be sure.

So I'm looking for some help or advice.

**Web browser downloaded CSV report**
```txt
"Empresa","Sistema","03/02/2022","pag.: 1" "","Relatorio de Mensagens - Periodo: de 01/01/2021 a 03/02/2022","13:15:12","" "" "DataInclusão","Assunto","Texto","Para","DataValidade","UsuárioManut" "14/07/2021","mensagem com arquivo","Enviando arquivo de teste:Atenciosamente","U:59384","14/07/2021","geynel" "14/09/2021","Feliz Dia do Cliente","","T:C","17/09/2021","geynel" "14/09/2021","Feliz Dia do Cliente","","T:S","17/09/2021","geynel" "" "Regs: ","3"

```
**$ file Download.csv** 
`Download.csv: Unicode text, UTF-8 text, with very long lines (456)`

**Server generated CSV report file at tmp dir**
```txt
"Empresa","Averba��o Eletr�nica","03/02/2022","pag.: 1"
"","Relatorio de Mensagens - Periodo: de 01/01/2021 a 03/02/2022","13:15:12",""
""
"DataInclus�o","Assunto","Texto","Para","DataValidade","Usu�rioManut"
"14/07/2021","mensagem com arquivo","Enviando arquivo de teste:Atenciosamente","U:59384","14/07/2021","geynel"
"14/09/2021","Feliz Dia do Cliente","","T:C","17/09/2021","geynel"
"14/09/2021","Feliz Dia do Cliente","","T:S","17/09/2021","geynel"
""
"Regs: ","3"

```
**$ file csv8uvJ51.csv**
`csv8uvJ51.csv: ISO-8859 text`

**Server generated XML report file at tmp dir**
```xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<RP TITLE="Relat�rio" BGCOLOR="#FFFFFF">
        <CSS >/lib/css/report.css</CSS>
<PG SZ="53" AL="LEFT" PN="1" PA="0" SP="0">
<R><C CC="DOCUMENT_LAYER" AL="LEFT" CS="1">Empresa</C><C CC="DOCUMENT_LAYER" AL="CENTER" CS="3">Averba��o Eletr�nica</C><C CC="DOCUMENT_LAYER" AL="CENTER">03/02/2022</C><C CC="DOCUMENT_LAYER" AL="RIGHT" CS="1">pag.: 1</C></R>
<R><C CC="PAGE_LAYER" AL="CENTER" CS="1"></C><C CC="PAGE_LAYER" AL="CENTER" CS="3" TC="REGULAR">Relatorio de Mensagens - Periodo: de 01/01/2021 a 03/02/2022</C><C CC="PAGE_LAYER" AL="CENTER">13:15:12</C><C CC="PAGE_LAYER" AL="CENTER" CS="1"></C></R>
<R><C CC="EVEN" CS="9"><XHTML><br></br></XHTML></C></R>
<R><C CC="PAGE_LAYER" TC="BOLD" WI="80px" AL="CENTER">DataInclus�o</C><C CC="PAGE_LAYER" TC="BOLD" WI="200px">Assunto</C><C CC="PAGE_LAYER" TC="BOLD" WI="410px">Texto</C><C CC="PAGE_LAYER" TC="BOLD" WI="200px">Para</C><C CC="PAGE_LAYER" TC="BOLD" WI="80px" AL="CENTER">DataValidade</C><C CC="PAGE_LAYER" TC="BOLD" WI="80px" AL="CENTER">Usu�rioManut</C></R>
<R><C CC="ODD" AL="CENTER">14/07/2021</C><C CC="ODD">mensagem com arquivo</C><C CC="ODD">Enviando arquivo de teste:Atenciosamente</C><C CC="ODD">U:59384</C><C CC="ODD" AL="CENTER">14/07/2021</C><C CC="ODD" AL="CENTER">geynel</C></R>
<R><C CC="EVEN" AL="CENTER">14/09/2021</C><C CC="EVEN">Feliz Dia do Cliente</C><C CC="EVEN"></C><C CC="EVEN">T:C</C><C CC="EVEN" AL="CENTER">17/09/2021</C><C CC="EVEN" AL="CENTER">geynel</C></R>
<R><C CC="ODD" AL="CENTER">14/09/2021</C><C CC="ODD">Feliz Dia do Cliente</C><C CC="ODD"></C><C CC="ODD">T:S</C><C CC="ODD" AL="CENTER">17/09/2021</C><C CC="ODD" AL="CENTER">geynel</C></R>
<R><C CC="EVEN" CS="9"><XHTML><br></br></XHTML></C></R>
<R><C CC="FOOTER" TC="BOLD" AL="CENTER">Regs: </C><C CC="FOOTER" TC="BOLD" AL="LEFT">3</C></R>
</PG>
</RP>
```
**$ file RptMensag4b087a8ab2149b53f5326e89433418bc**
`RptMensag4b087a8ab2149b53f5326e89433418bc: XML 1.0 document, ISO-8859 text, with very long lines`

**Nginx/PHP log at CSV generation/download**
```php
10.0.1.207 - - [03/Feb/2022:13:26:14 -0300] "POST /websys/php/read.php?_dc=1643905574528 HTTP/1.1" 200 229 "https://wws.sistema.com.br/websys/?comp=5" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
2022/02/03 13:26:14 [error] 23#23: *291554 FastCGI sent in stderr: "PHP message: PHP Warning:  DOMDocument::load(): Empty string supplied as input in /www/www/php/libs/phpreports/PHPReportsUtil.php on line 204PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getFileName() on null in /www/www/php/libs/phpreports/PHPReportMaker.php(288) : eval()'d code:74

Stack trace:
#0 /www/www/php/libs/phpreports/PHPReportMaker.php(310): PHPReport->run()
#1 /www/www/php/report.php(62): PHPReportMaker->run()
#2 /www/www/php/conn.php(59): require('/www/www/php/re...')

}
  thrown in /www/www/php/libs/phpreports/PHPReportMaker.php(288) : eval()'d code on line 74" while reading response header from upstream, client: 10.0.1.207, server: www.sistema.*, request: "POST /php/conn.php HTTP/1.1", upstream: "fastcgi://10.0.1.13:9000", host: "wws.sistema.com.br", referrer: "https://wws.sistema.com.br/index.html?comp=5"
10.0.1.207 - - [03/Feb/2022:13:26:14 -0300] "POST /php/conn.php HTTP/1.1" 500 526 "https://wws.sistema.com.br/index.html?comp=5" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36"
```

Any ideas of "where to look at" are very welcome.

**Comment by taq** [comment]
To be honest I even forgot it exports as CSV. :-)
If you try to run it on the command line, you also get some kind of error?

**Comment by EthraZa** [comment]
Sorry if it seens a dumb question, but...
How do I run the report on command line?

If you are saying `php system_index.html` that would be dificult to do. The report runs inside an iframe but with some variables and structures mounted for the logged in user. Maybe I could create a php file that mimic all this, but... auch.
Maybe I'm think in the worng way, not sure... this is an old system too,

**Comment by taq** [comment]
I used to test it on CLI before going to the server. I'll try to make it tomorrow and tell if it worked. I'm not using PHP for years! :-D

**Comment by EthraZa** [comment]
I just found out that, if I right click on the report and go to "View frame source" the report text will show ok, with all line breaks.

This is confusing, the same browser show different things in the old and new system. I'm still guessing UTF-8 vs ISO-something is biting my ancles again.

Adding \<pre\> tag to the CSV iframe body makes it shows right. There is a simple way to tell phpreports to add \<pre\> tags around text outputs but the html one?

**Comment by EthraZa** [comment]
Ok, I have edited files output/*/PHPReportOutput.php and changed line ~50:
`print $sText;`
to
`print '<pre>'.$sText.'</pre>';`

The error 500 are still there, but at least users wont complain anymore.

**Comment by taq** [comment]
Guys, can we close this issue so? I declared PHPReports as abandonware, I don't use PHP for years and can't keep it going.
